### ISSUE TITLE
[BUG] Pf1e Buff duration advance in Combat is broken

### ISSUE THREAD

**Issue by Hevkalo1** [vigoren/foundryvtt-simple-calendar#620] opened 2024-06-27 21:56 UTC
Simple Calendar advances Buffs per turn instead of per round with Seconds per Combat Round set to more than zero.
If you set it to zero then Ui buttons does not advance time with rounds option.
**To Reproduce**

1. Set Seconds per Combat to 6
2. Make Combat with several PC/NPC
3. Add buff with duration
4. Advance turn

**Expected behavior**

Buff advances only on start of player turn

https://github.com/vigoren/foundryvtt-simple-calendar/assets/148167540/1c2ec0ee-966a-4bf4-b3cd-05e486d62be1
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/148167540/927f4d1e-1c9f-48b6-9b83-45d494a6ffaf)

**Foundry Information**
 - Foundry Version: 11.315
 - Game System: Pf1e v10.3
 - Simple Calendar Version: 2.4.18

**Browser (please complete the following information):**
 - Browser latest chrome/foundry server client

**Comment by mkahvi** [comment] 2024-07-16 00:07
It seems like the setting is ignoring Foundry's time passing configuration in `CONFIG.time.roundTime` despite the hint text claiming it heeds it.

**Comment by dmrickey** [comment] 2024-07-16 19:03
Please fix this.. There are questions about "why are my buffs ending early?" practically every day in the pf1 discord.

**Comment by vigoren** [comment] 2024-07-19 00:19
Sorry about the long delay I'll be looking into this tonight.

**Comment by vigoren** [comment] 2024-07-20 04:52
I have tried and been unable to replicate this issue in PFE 10.3 or 10.4

I created a combat with PC's and NPC's gave one a buff and advanced combat rounds and everything is adjusting as expected.

Could someone provide me with detailed step by step on how to reproduce (I don't play PFE 1 on foundry) or an example world with the issue?

**Comment by mkahvi** [comment] 2024-07-20 08:11
On quick testing I can not reproduce it either (with default settings nor with Golarion 1e preset). I don't use the module, so I've been mostly just watching from the side and trying to help people locate the module that causes the problem. But since adjusting the seconds per combat round to zero has fixed it for everyone who has had it, I dunno 🤷🏻

**Comment by mkahvi** [comment] 2024-07-24 19:48
Recent discoveries have found that async code and combat updates don't go very well together.

This bug is although Somehow made worse by simple calendar specifically, appears to be in system code due to how weirdly Foundry handles combat updates that also update time (cycling turns/rounds).

So you have my blessing to close this as not being fault of your module.

PF1 v10.5 will hopefully [have this fixed](<https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/merge_requests/3297>) by more rigorously guarding against Foundry's weird behaviour.

Noticed this only because I was fixing a very specific bug that hinted at the oddity.

**Comment by Hevkalo1** [comment] 2024-08-20 17:08
@vigoren Fixed with the latest release of pf1 system.

**Closed as completed** 2024-08-20 17:09 UTC
Labels: bug
