### ISSUE TITLE
move time only changes time after clicking stop advancing time [BUG] 

### ISSUE THREAD

**Issue by dharkus5000** [vigoren/foundryvtt-simple-calendar#576] opened 2024-02-07 23:21 UTC
**Describe the bug**
today when i got in game simple calendar opened automatically as usual, i later pressed esc and accidentally closed it and reopened it from the settings, from then on the time would only change after clicking move time (forwards or backwards) after clicking stop advancing time button, at which point the amounts of time i'd added to the time updated properly, incl if i'd clicked a button multiple times while the time wasn't changing

**Foundry Information**
 - Foundry Version: 11.315
 - Game System: PF2e 5.13.3
 - Simple Calendar Version: 2.4.3
 - Simple Calendar Configuration: using in compact mode, have changed names of months in golarion calendar to reflect a tian-xia campaign

**Browser (please complete the following information):**
 - FF 122.0 (update is available...)

**Comment by rapus95** [comment] 2024-02-23 01:08
I also get this issue for dnd5e. Simple Calendar only updates its visuals when the real time clock ticks. So once per second and only if the real time progression is enabled. As soon as you stop the real time progression, it won't update day or time even if using the simple calendar buttons to progress an hour or a day. Meanwhile, the smalltime window right next to it successfully updates on each click within simple calendar in live sync.

**Comment by rapus95** [comment] 2024-02-23 01:58
Having edited both lines to true with Chrome Dev Tools, made the clock update again. But then deleting my changes, refreshing the page and even trying in an incognito browser, it kept working... Which is weird.

So I'm back at the beginning and have no clue what the problem is.

**Comment by vigoren** [comment] 2024-02-28 05:25
I will be digging into this issue, and a few others, over the weekend when I have some free time.

**Comment by vigoren** [comment] 2024-03-03 05:09
I have found the issue and will be releasing a fix for it in a couple of days (after I fix up a few other things)

**Comment by vigoren** [comment] 2024-03-08 04:44
This has been fixed in version 2.4.8!

**Closed by vigoren** 2024-03-08 04:44 UTC
Labels: bug
