### ISSUE TITLE
[BUG] Year does not change when "Change to Next Month" rolls over.

### ISSUE THREAD

**Issue by jonathanmclaus** [vigoren/foundryvtt-simple-calendar#274] opened 2022-01-29 19:59 UTC
**Describe the bug**
When I click "Change to Next Month" repeatedly, the year mentioned in the calendar at the top left never changes, even though it is clear that under the hood the year is changing. Cycling through years shows the correct notes, holidays, and calendars, but the year at the top left stays the same and that is very confusing.

**To Reproduce**
I am using the Pathfinder 1E / Golarion calendar.

1. Open the calendar.
2. Click "Change to Next Month" repeatedly.
3. Observe that the data displayed changes but not the year in the top left.

**Expected behavior**
The year should change.

**Screenshots**
This screenshot demonstrates one example. After cycling through a full year with the Change to Next Month buttons, the year still says 4719 at the top left, but when editing notes the bottom display correctly states "Notes for ... 4720".
![image](https://user-images.githubusercontent.com/5731591/151675738-8fb2cc2e-a326-4c35-af1d-ef65e2fc6f63.png)

**Foundry Information**
 - Foundry Version: 9.242]
 - Game System: PF1E
 - Simple Calendar Configuration: Golarion

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: I'm only using the standalone application.

**Comment by vigoren** [comment] 2022-01-31 00:44
This issue will be fixed in the next release. Closing this as it is a duplicate of #242.

**Closed by vigoren** 2022-01-31 00:44 UTC
Labels: bug
