### ISSUE TITLE
[BUG] PF2e expired effects on actors cause increased CPU load and Stuttering while actor sheet open

### ISSUE THREAD

**Issue by tuhs1985** [vigoren/foundryvtt-simple-calendar#429] opened 2023-01-02 06:27 UTC
**Describe the bug**
Using the PF2e System.  With the actor sheet open, when an effect on an actor expires while the game clock is running, the CPU usage goes to 100% and it becomes difficult to navigate (scrolling, zooming).  Pausing game clock and/or removing the expired effect removes the issue.

**To Reproduce**
1. While paused, game clock not running, using the Pathfinder 2E system, place an effect (such as Spell Effect: Soothe) onto the actor.  Leave actor sheet open
2. Advance game clock until effect expires.
3. Un pause and start game clock.
4. Attempt to zoom in/out or to scroll a page.  CPU usuage should be high, and zooming/scrolling should stutter

**Expected behavior**
CPU usage should jump from its normal range to nearly 100% and scrolling/zooming should stutter.  Pausing game clock will return cpu usage to normal range.  Removing expired effect will also return cpu usage to normal range

**Screenshots**
![image](https://user-images.githubusercontent.com/77306309/210199875-693f126f-29eb-4393-b5a8-241c7259aa2d.png)

**Foundry Information**
 - Foundry Version:  V10, 291 
 - Game System:  PF2E 4.6.1
 - Simple Calendar Version: 2.1.60

**Browser (please complete the following information):**
 - Chromium Edge

**Additional context**

**Comment by vigoren** [comment] 2023-01-04 22:31
Hey! I haven't seen it hard if an issue like this before, but that doesn't mean it isn't a bug.

My first question would be if the issue persists with all other modules disabled? This just helps narrow what might be the cause is the issue and there could be another module also doing something while the clock is running that might be interfering.

If it is still an issue then I would be curious to know if it happens only while the clock is running or if manually advancing time can also cause a similar issue.

I will try to reproduce it on my end as well.

**Comment by tuhs1985** [comment] 2023-01-05 02:34
To answer your question, I was able to duplicate it on a fresh instance of foundry on forge. the only other module running is "the forge" (which I can't disable).  It only occurs when the clock is running.  I can manually advance the clock with it paused and suffer no performance issues.  

Honestly, I stumbled acrossed it by complete accident.

**Comment by tuhs1985** [comment] 2023-01-05 02:41
I should mention, I was viewing CPU usage using the performance monitor w/in chrome

**Comment by vigoren** [comment] 2023-01-05 07:33
Thanks for answering my questions and the additional information.

I'll try and replicate it to see what's going on here as it shouldn't be locking up the cpu.

**Comment by tagnullde** [comment] 2023-01-31 22:21
I can confirm the stuttering in the character sheet in Pathfinder 2e.
I can't confirm the CPU load (but I have a beefy rig, so maybe not showing up)

In 5e I have some glitches when moving the compact calendar around on the canvas and increased CPU load (well, CPU fans spin up - which is unusual in my experience) then. Not sure if that's related or maybe to be expected.

Google-Chrome under Ubuntu was used. Everything is up to date.

**Comment by vigoren** [comment] 2023-02-04 07:32
@tuhs1985 I have been unable to reproduce any sort of significant load on my computer to replicate this issue. But that is probably because I do not play PF2E so my world is very light (1 actor and the condition). Would it be possible for you to zip up your world and send it to me?

If not that is all good, I would ask that you disable Simple Calendar and try running this in your browser console. It is a very basic function to advance time by 1 second every second. `window.setInterval(() => {game.time.advance(1)}, 1000);` (It will run forever but refreshing the browser will stop it)

If the issue continues to happen when this is running that will help narrow it down to something going on with another module or the PF2E system itself. If it doesn't happen then it is something going on in my code and it will help me narrow things down a bit.

**Comment by vigoren** [comment] 2023-07-10 21:11
Closing this for now, please reopen if more details come up.

**Closed by vigoren** 2023-07-10 21:11 UTC
Labels: bug
