### ISSUE TITLE
[BUG]  Simple calendar causes double client side messages to be posted

### ISSUE THREAD

**Issue by roi007leaf** [vigoren/foundryvtt-simple-calendar#588] opened 2024-03-11 03:12 UTC
**Describe the bug**
In the latest version of Pf2e while using simple .calendar I get double persistent damage applied and double recovery check 

**To Reproduce**
Set persistent damage on monster. 
Pass a turn so combatant will get persistent damage. 

**Expected behavior**
Only one message is posted

**Screenshots**

**Foundry Information**
 - Foundry Version: latest 
 - Game System: pf2e
 - Simple Calendar Version: 2.4.9
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
Chrome

**Additional context**

**Comment by Peach774** [comment] 2024-03-11 06:22
This is a conflict with PF2e Toolbelt, not workbench

**Comment by roi007leaf** [comment] 2024-03-11 06:27
Just checked and 2.4.3 the bug doesn't happen

**Comment by Peach774** [comment] 2024-03-11 06:27
Yeah I want to expand on this a bit - it isn't a cross-module conflict. This occurs with ONLY simple calendar and pf2e. It isn't persistent damage duplicating or anything that sinister. It is chat messages duplicating clientside

**Comment by roi007leaf** [comment] 2024-03-11 06:35
after testing a bit this is the code change that made this bug happen @vigoren 
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/17231451/a13d2f05-bbcb-4035-aeec-97aa9b6d3c4b)
reverting to precreate fixes it

**Comment by vigoren** [comment] 2024-03-12 02:37
I have tracked down what seems to be the issue and am just spending some time running a few more tests to make sure nothing is double posted. An update should be released in roughly 24 hours at the latest.

**Comment by vigoren** [comment] 2024-03-14 03:29
Sorry had some personal stuff come up yesterday but version 2.4.12 should address this. Please let me know if it doesn't

**Comment by roi007leaf** [comment] 2024-03-14 05:39
@vigoren you made it worse now it's actually doing everything twice.. recovery checks and damage instead of just showing duplicate chat messages XD

**Comment by vigoren** [comment] 2024-03-14 05:53
Then I am having difficulty replicating the issue as on my test version of PF2E I don't get duplicate messages for anything. Do you have a very simple example that can replicate it?

Your proposed fix causes errors with other systems, which is why I changed it.

**Comment by roi007leaf** [comment] 2024-03-14 05:55
Make an encounter with just 1 monster, no pcs.
Set persistent damage on it of any kind.
Start the encounter.
Pass a turn.
You need to have workbench persistent damage automation turned on, or roll recovery check yourself.

**Comment by vigoren** [comment] 2024-03-14 06:15
Thank you. Must have done something wrong the first time but now the messages are duplicated.

Interestingly it seems to only duplicate the first persistent damage roll and the first recovery check. Afterwards it does just single chat cards.

The damage appears to only be applied once though so it isn't duplicating anything other than the chat card.

Ok back to the drawing board I will keep digging into what is going on here. Sorry about this

**Comment by roi007leaf** [comment] 2024-03-14 06:51
No problem, if I can help in any way, let me know

**Comment by ariakas2008** [comment] 2024-03-15 09:07
I can confirm this bug, it happens with some of the features of pf2 workbench, such 
"Automatically apply persistent damage"
"..and automatically roll recovery after that"
"Automatically apply persistent healing rolled by the system"

**Comment by vigoren** [comment] 2024-03-16 21:06
Ok this should be addressed now in version 2.4.13

I ended up going  back to how this worked in 2.4.3 (which was released September 2023 and seemed to not have this issue at all) and then reapproached the original issue that caused me to change it. So all of the reported issues should be fixed.

**Comment by ariakas2008** [comment] 2024-03-17 12:57
> Ok this should be addressed now in version 2.4.13
> 
> I ended up going back to how this worked in 2.4.3 (which was released September 2023 and seemed to not have this issue at all) and then reapproached the original issue that caused me to change it. So all of the reported issues should be fixed.

I can confirm it's fixed, thank you!

**Closed** 2024-03-17 18:13 UTC
Labels: bug
